<a href="https://colab.research.google.com/github/iamisha/Python-Project-2024/blob/branch-test-2/vectorized_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Vectorized operations**

In [3]:
np.arange(1000000).sum() # It calculates the sum of all the elements (0 to 9999999)in that array.

499999500000

**Adding 3 to each element of the array using numpy**

In [4]:
array = np.array([[1,2,3], [4,5,6]])
array + 3

array([[4, 5, 6],
       [7, 8, 9]])

**Multiplyng by a scalar**

In [5]:
array = np.array([[1,2,3], [4,5,6]])
array * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [6]:
array_a = np.array([[1,2,3], [4,5,6]])
array_b = np.array([[2,3,4], [1,2,3]])
array_a + array_b

array([[3, 5, 7],
       [5, 7, 9]])

**Multiplying two arrays together**

In [7]:
array_a = np.array([[1,2,0], [4,5,0]])
array_b = np.array([[0,3,4], [1,2,3]])
array_a * array_b

array([[ 0,  6,  0],
       [ 4, 10,  0]])

**Boolean mask**

In [8]:
array_a = np.array([[1,2,0], [4,5,0]])
array > 2

array([[False, False,  True],
       [ True,  True,  True]])

**Vectorize Python code**

In [9]:
array = np.array(["NumPy", "is", "awesome"])
len(array) > 2

True

In [10]:
vectorized_len = np.vectorize(len)
vectorized_len(array) > 2

array([ True, False,  True])