In [4]:
import numpy as np

**Indexing 1D arrays**

In [5]:
array = np.array([2,4,6,8,10])
array[3]

8

**Indexing elements in 2D**


In [7]:

# Create an empty Sudoku grid
sudoku_game = np.zeros((9, 9), dtype=int)

# Fill in some initial values (example)
sudoku_game[0, 1] = 5
sudoku_game[0, 7] = 3
sudoku_game[1, 2] = 9
# Fill in more values as needed...

# Print the Sudoku grid
print(sudoku_game)


# indexing elements in 2D
sudoku_game[1,2]


[[0 5 0 0 0 0 0 3 0]
 [0 0 9 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


9

**Indexing rows in 2D**

If we give NumPy just one index when indexing a 2D array, it assumes that the index is a row index

In [9]:
sudoku_game[1]

array([0, 0, 9, 0, 0, 0, 0, 0, 0])

**Indexing columns in 2D**

In [11]:
sudoku_game[:,1]

array([5, 0, 0, 0, 0, 0, 0, 0, 0])

**Slicing 1D array**

In [12]:
array = np.array([2,4,5,8,10])
array[2:4]

array([5, 8])

**Slicing elements in 2D**

In [23]:

# Create an empty Sudoku grid
sudoku_game = np.zeros((9, 9), dtype=int)

# Fill in some initial values (example)
sudoku_game[0, 1] = 5
sudoku_game[0, 7] = 3
sudoku_game[1, 2] = 9
sudoku_game[0, 3] = 8
sudoku_game[2, 7] = 9
sudoku_game[5, 2] = 3
sudoku_game[2, 1] = 11
sudoku_game[2, 7] = 3
sudoku_game[1, 2] = 9
# Fill in more values as needed...

# Print the Sudoku grid
print(sudoku_game)


# slicing elements in 2D
sudoku_game[0:3, 0:3]

[[ 0  5  0  8  0  0  0  3  0]
 [ 0  0  9  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]


array([[ 0,  5,  0],
       [ 0,  0,  9],
       [ 0, 11,  0]])

**Slicing with steps**

In [24]:
# Print the Sudoku grid
print(sudoku_game)


# slicing with steps
sudoku_game[3:6:2, 3:6:2]

[[ 0  5  0  8  0  0  0  3  0]
 [ 0  0  9  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]


array([[0, 0],
       [0, 0]])

**Sorting arrays**

The np.sort() function sorts an arrya along a given axis

* default sort by column

In [26]:
np.sort(sudoku_game)

array([[ 0,  0,  0,  0,  0,  0,  3,  5,  8],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9],
       [ 0,  0,  0,  0,  0,  0,  0,  3, 11],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  3],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]])

* to sort the array by row, set the axix keyword arguement to zero

In [28]:
print(sudoku_game)
np.sort(sudoku_game, axis = 0)

[[ 0  5  0  8  0  0  0  3  0]
 [ 0  0  9  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  5,  3,  0,  0,  0,  0,  3,  0],
       [ 0, 11,  9,  8,  0,  0,  0,  3,  0]])