In [ ]:
import torch

In [ ]:
lst = [[2,3,4],[5,6,7]]
tensor = torch.tensor(lst)
tensor.shape

torch.Size([2, 3])

In [ ]:
torch.device

torch.device

In [ ]:
torch.Storage

torch.FloatStorage

In [ ]:
torch.dtype

torch.dtype

In [ ]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
a + b

tensor([[ 6,  8],
        [10, 12]])

In [ ]:
tensor.dtype

torch.int64

**Exercise 1**


**Creating tensors and accessing attributes**
Tensors are the primary data structure in PyTorch and will be the building blocks for our deep learning models. They share many similarities with NumPy arrays but have some unique attributes too.

In this exercise, you'll practice creating a tensor from a Python list and displaying some of its attributes.

In [1]:
# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)

print(tensor_a)

tensor([1, 2, 3, 4])


In [2]:
# Display the tensor device
print(tensor_a.device)

# Display the tensor data type
print(tensor_a.dtype)

cpu
torch.int64


**Exercise 2**

**Creating tensors from NumPy arrays**

Tensors are the fundamental data structure of PyTorch. You can create complex deep learning algorithms by learning how to manipulate them.

The torch package has been imported, and two NumPy arrays have been created, named array_a and array_b. Both arrays have the same dimensions.

In [5]:
arr_a = ([[2,3,4],[5,6,7]])
arr_b = ([8,9,2], [0,1,3])

# Create two tensors from the arrays
tensor_a = torch.tensor(arr_a)
tensor_b = torch.tensor(arr_b)

# Subtract tensor_b from tensor_a
tensor_c = tensor_a - tensor_b

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b

# Add tensor_c with tensor_d
tensor_e = tensor_c + tensor_d

print(tensor_e)




tensor([[10, 21, 10],
        [ 5, 11, 25]])
